export {default as Board} from './board/index'
export {default as RegisterQueue} from './register-queue/index'
export {default as DashboardUser} from './dashboard-user/index'
export {default as Operator} from './operator/index'
export {default as NotFound} from './404/index'
export {default as Blocked} from './blocked/index'
export {default as ScanBarcode} from './scan-barcode/index'